### ISSUE TITLE
商品列表，后台好多报错的，是不是没传完

### ISSUE THREAD

**Issue by encone** [sqc157400661/XiaoTShop#1]
Base table or view not found: 1146 Table 'xiaot.goods' doesn't exist (SQL: select count(*) as aggregate from `goods`)

**Comment by sqc157400661** [comment]
数据没传完，稍后我在上传下

**Comment by encone** [comment]
migrations 里面还是没有传完
QLSTATE[42S02]: Base table or view not found: 1146 Table 'xiaot.goods' doesn't exist (SQL: select count(*) as aggregate from `goods`)，
我加你微信了，

**Comment by sqc157400661** [comment]
需要执行下最新的seed   拉下最新代码后执行php artisan db:seed。
